Repository IT4Change/boilerplate-frontend, pull requests merged in 2024-05, with the labels that each got.

#206 refactor(frontend): use our vuepress deployment action in docs deployment workflow
  .github/workflows/frontend.deploy.docs.yml
Labels: enhancement, good first issue, github_actions

#220 chore(frontend): update packages 2024 05 06
  package-lock.json
  package.json
Labels: dependencies

#241 chore(frontend): update packages 2024 05 12
  package-lock.json
  package.json
Labels: dependencies

#242 refactor(frontend): dependabot group updates
  .github/dependabot.yml
Labels: enhancement, dependencies

#248 refactor(frontend): refine dependabot groups
  .github/dependabot.yml
Labels: enhancement, dependencies

#261 refactor(frontend): refine dependabot groups
  .github/dependabot.yml
Labels: enhancement, dependencies

#272 chore(frontend): remove unused dependency
  package-lock.json
  package.json
Labels: dependencies

#278 ci(other): refine dependabot eslint group
  .github/dependabot.yml
Labels: enhancement, dependencies

#280 ci(workflow): refine deploy docs workflow
  .github/file-filters.yml
  .github/workflows/frontend.deploy.docs.yml
Labels: enhancement

#281 ci(workflow): refine deploy docs workflow
  .github/workflows/frontend.deploy.docs.yml
Labels: enhancement
